services:
  copy_files:
    build: .
    restart: "no"
    depends_on:
      - init

  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"

    environment:
      # Server settings
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: "1.20"
      USE_AIKAR_FLAGS: true
      SNOOPER_ENABLED: false

      # Server metadata
      ONLINE_MODE: false
      SERVER_NAME: "Les potes: V2"
      ICON: /config/icon.png
      MOTD: "Bienvenue chez &o&3Les Potes: Saison 2 Remake revisée : L'intégrale Blu-Ray !\nHébergé par &4lydia39&7."
      
      # Game settings
      DIFFICULTY: normal
      VIEW_DISTANCE: 20

      # Whitelist
      ENABLE_WHITELIST: true
      WHITELIST_FILE: /config/whitelist.txt
      
      # RCON
      RCON_PASSWORD: $PASSWORD_RCON
      
      # Mods
      MODRINTH_PROJECTS: |
        lithium
        modernfix
      MODRINTH_ALLOWED_VERSION_TYPE: release

    volumes:
      - mc_data:/data
      - type: bind
        read_only: true
        source: config
        target: /config
        bind:
          create_host_path: true

volumes:
  mc_data:
