[general]
botToken = "${CFG_DISCORD_BOT_TOKEN}"
# The channel ID where the bot will be working in
botChannel = "1261381896189906946"
# PLACEHOLDERS:
# %online% - Online Players
# %max% - Maximum Player Amount
botStatusName = "%online%/%max% joueurs en ligne"
botStatusNameSingular = "Seulement %online% joueur..."
botStatusNameEmpty = "Personne n'est en ligne..."
# Allowed Values: DISABLED,PLAYING,WATCHING,LISTENING,STREAMING,COMPETING,CUSTOM
botStatusType = "CUSTOM"
streamingURL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
enableUpdateChecker = true
# Allowed values: release, beta, alpha
updateCheckerMinimumReleaseType = "release"
allowConfigMigration = true
# Set to true to suppress warning of unsafe mod download location
ignoreFileSource = false
# Set to true to allow relaying webhook messages
allowWebhookMessages = false
# Set to false to disable automatic config tweaking to fix known issues
# Your config file will not be sent anywhere during this
# This feature is not implemented yet
allowAutomaticBugFixing = true

[compatibility]
# Disables modifying sent chat messages in-game to show who was pinged. (Will not convert <@1234567890> to @User)
# This may fix mods also modifying sent messages
disableParsingMentionsIngame = false

[commands]
enabled = true
adminRoleIDs = ["1262351061000261712"]

# Add your custom commands here
# You can also generate some on https://erdbeerbaerlp.de/dcintegration-commands/

listCmdEnabled = true
hideListCmd = false  # Ephemeral message
uptimeCmdEnabled = true
hideUptimeCmd = false
useLocalCommands = false

[[commands.customCommands]]
name = "kick"
description = "Kicks an player from the Server"
mcCommand = "kick %player% %reason%"
textToSend = ""
adminOnly = true
hidden = false

[[commands.customCommands.args]]
name = "player"
description = "The player to be kicked"
optional = false

[[commands.customCommands.args]]
name = "reason"
description = "Reason for the kick"
optional = true

[[commands.customCommands]]
name = "stop"
description = "Stops the server"
mcCommand = "stop"
textToSend = ""
adminOnly = true
hidden = false
args = []

[[commands.customCommands]]
name = "kill"
description = "Kills an Player or Entity"
mcCommand = "kill %target%"
textToSend = ""
adminOnly = true
hidden = false

[[commands.customCommands.args]]
name = "target"
description = "The target(s) for the kill command."
optional = false

[messages]
language = "fr-FR"
sendOnSayCommand = true
sendOnMeCommand = true
# Adding an selector (ex. @a ) here will relay all /tellraw messages sent with that exact same selector to discord.
# Leave blank to disable
tellrawSelector = ""
sayCommandIgnoredPrefix = "§4§6§k§r"
discordRoleColorIngame = true
enableHoverMessage = true
charBlacklist = ["࿕", "࿖"]

[embedMode]
enabled = true

[embedMode.startMessages]
asEmbed = true
colorHexCode = "#57f287"
# Check the documentation at https://wiki.erdbeerbaerlp.de/dcintegration:custom-embeds.
customJSON = ""

[embedMode.stopMessages]
asEmbed = true
colorHexCode = "#ed4245"
customJSON = ""

[embedMode.playerJoinMessage]
asEmbed = true
colorHexCode = "#57f287"
customJSON = ""

[embedMode.playerLeaveMessages]
asEmbed = true
colorHexCode = "#ed4245"
customJSON = ""

[embedMode.deathMessage]
asEmbed = true
colorHexCode = "#000000"
customJSON = ""

[embedMode.advancementMessage]
asEmbed = true
colorHexCode = "#fee75c"
customJSON = ""

[embedMode.chatMessages]
generateUniqueColors = true
asEmbed = true
colorHexCode = "#808080"
customJSON = ""

[advanced]
serverChannelID = "default"
deathsChannelID = "default"
chatOutputChannelID = "default"
chatInputChannelID = "default"
baseAPIUrl = "https://discord.com"

[forgeSpecific]
IMC_modIdBlacklist = ["examplemod"]
sendItemInfo = true

[linking]
enableLinking = false
unlinkOnLeave = true
shouldNickname = false
globalLinking = false
databaseClass = "de.erdbeerbaerlp.dcintegration.common.storage.linking.database.JSONInterface"
# Role ID of an role an player should get when he links his discord account
# Leave as 0 to disable
linkedRoleID = "0"
whitelistMode = true
requiredRoles = []
settingsBlacklist = []

[linking.personalSettingsDefaults]
default_useDiscordNameInChannel = true
default_ignoreReactions = false
default_pingSound = true

[webhook]
enable = false
serverAvatarURL = "https://minecraft.wiki/images/Material_Reducer_%28S%29_BE1.png"
serverName = "Serveur"
useServerNameForRcon = true
useServerNameForConsole = true

# PLACEHOLDERS:
# %uuid% - Returns the player's UUID with dashes
# %uuid_dashless% - Returns the player's UUID without dashes
# %name% - Returns the player's name
# %randomUUID% - Returns an random UUID which can be used to prevent discord cache
# https://www.tydiumcraft.net/docs/skinapi supports both bedrock(floodgate) and java players
# Default - https://api.tydiumcraft.net/v1/players/skin?uuid=%uuid%&type=avatar&randomuuid=%randomUUID%
playerAvatarURL = "https://api.mineatar.io/head/%uuid%?scale=8"
webhookName = "MC_DC_INTEGRATION"

[ingameCommand]
enabled = true
message = "Rejoindre le &9Discord&f : &b&nhttps://discord.gg/3PCTu2qEjU"
hoverMessage = "Cliquer ici pour rejoindre le serveur"
inviteURL = "https://discord.gg/3PCTu2qEjU"

[commandLog]
channelID = "0"
# The format of the log messages
#
# PLACEHOLDERS:
# %sender% - The name of the Command Source
# %cmd% - executed command (e.g. "say Hello World"
# %cmd-no-args% - Command without arguments (e.g. "say"
message = "%sender% executed command `%cmd%`"
ignoredCommands = ["list", "help", "?"]
commandWhitelist = false

[votifier]
enabled = false
votifierChannelID = "default"
message = ":ballot_box: %player% just voted on %site%"
name = "Votifier"
avatarURL = "https://www.cubecraft.net/attachments/bkjvmqn-png.126824/"

[dynmap]
# PLACEHOLDERS:
# %sender% - The sender´s name
# %msg% - The Message
dcMessage = "<%sender%> %msg%"
dynmapChannelID = "default"
name = "Dynmap Web-Chat"
avatarURL = "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/91/Map_Zoom_0.png/revision/latest?cb=20200311153330"
# PLACEHOLDERS:
# %name% - The discord name of the sender (including nickname)
# %name#tag% - The discord name with tag of the sender (without nickname)
webName = "%name% (discord)"
# Name shown in discord when no name was specified on the website
unnamed = "Unnamed"

[bstats]
sendAddonStats = false

[bungee]
isBehindBungee = false
